### ISSUE TITLE
C Demo does not work in Ubuntu

### ISSUE THREAD

**Issue by szagoruyko** [CRVI/OpenCLIPP#11]
Hello, I have tried to run C++ and C demos in Ubuntu, C++ works fine but C Test-OpenCLIIPP gives black images on Intel and garbage on Nvidia. No filters work in C side in fact.
I wanted to run test but failed to compile them.

**Comment by AntAgna** [comment]
Thank you for reporting this.
The C version of the library calls the C++ version.
So the Test-OpenCLIPP program ends up doing the same thing and uses the same .cl files as the C++ version.
If one works properly, I would expect the other to also work.
Are you sure you have set the path of the .cl files properly using ocipSetCLFilesPath() ?
If you check the return values (ocipError) of the ocip functions, do you see an error code ?
You can check the return values by using a debugger or by adding printf()s in the program.
(Error handling was not added to keep the example program simple).

Testing on Linux has mostly been done using the AMD OpenCL platform so it is possible that there are problems when using the Intel or Nvidia platforms on Linux.

When you say you failed to compile, do you mean the C program or the OpenCL files ?
What compiler error go you get ?

**Comment by szagoruyko** [comment]
Hi Antoine, thanks for the reply.
C++ Demo works fine producing the filtered image on Intel and Nvidia, so I am assuming that C version should work too. I am sure that C version gets the right cl-files, that's the same path as in C++ Demo.
All the return values are CL_SUCCESS, I added printfs.

I am using gcc-4.8 with OpenCL 1.1 driver from CUDA distribution. I failed to compiled tests with OpenCV and IPP and couldn't find any information how to do that properly.

Noticed a few weird things in C wrapper:
* https://github.com/CRVI/OpenCLIPP/blob/master/OpenCLIPP/OpenCLIPP.cpp#L307 It says filters, but morphology provided
* the same place, ocipPrepareTransform is missing, giving the link error.

I want to use the library in [Torch](http://torch.ch) framework and have written a small lua wrapper over C functionality, if it would work that would be an awesome addition for us.

**Comment by szagoruyko** [comment]
I believe there is an issue with casting to ColorImage in OpenCLIPP.cpp, because grayscale images work fine

**Comment by AntAgna** [comment]
Thank you for reporting this.
Unfortunately, I will be unable to work on this until July 20th.
In the mean time, feel free to fix these problems in the code and send us a pull request.

**Comment by szagoruyko** [comment]
ok I understand it now. I thought you were storing ColorImages with the number of channels given but in fact you always expect 4-channel images. To fix the demo you have to add the 4th channel somehow, I  don't know how it's done in C++ demo.
The problem is in Torch we usually operate on 3HW or HW tensors and converting them to HW4 and back is a bit of a pain.. Anyways, the functionality is nice and I will finish the wrapper.

**Comment by AntAgna** [comment]
ColorImage is only for 3 channel images.
Images that have 1, 2 or 4 channels use the Image class instead.
ColorImage converts to 4 channel when sending data to the GPU and back to 3 channel when reading the data back to the host.

The conversion is done in the GPU so the overhead should be small.
The overhead is lower than using unaligned 3 channel memory access for many of the primitives (especially for small data types).

In the C++ Demo, we load a 3 channel image from a .png file and we create a ColorImage with it.

In the C demo project, we also load a 3 channel image from a .png file.
In the C interface, ocipCreateImage() will create a ColorImage object when given 3 channel data and a Image object otherwise.
So using 3 channel images with the C interface should be transparent.

I will update the documentation.

Thank you for the fix in the pull request.
